<!DOCTYPE html>
<html>

    <head>
        <meta name="layout" content="main"/>
        <title>Welcome to Grails</title>
    </head>

    <body>
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span3">
              <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Application Status</li>
                    <li>App version: <g:meta name="app.version"/></li>
                    <li>Grails version: <g:meta name="app.grails.version"/></li>
                    <li>Groovy version: ${org.codehaus.groovy.runtime.InvokerHelper.getVersion()}</li>
                    <li>JVM version: ${System.getProperty('java.version')}</li>
                    <li>Reloading active: ${grails.util.Environment.reloadingAgentEnabled}</li>
                    <li>Controllers: ${grailsApplication.controllerClasses.size()}</li>
                    <li>Domains: ${grailsApplication.domainClasses.size()}</li>
                    <li>Services: ${grailsApplication.serviceClasses.size()}</li>
                    <li>Tag Libraries: ${grailsApplication.tagLibClasses.size()}</li>
                    <li class="nav-header">Installed Plugins</li>
                    <g:each var="plugin" in="${applicationContext.getBean('pluginManager').allPlugins}">
                        <li>${plugin.name} - ${plugin.version}</li>
                    </g:each>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
            <div class="span9">
              <div class="hero-unit">
                <h1>Welcome to Grails</h1>
                <p>Congratulations, you have successfully started your first Grails application with Twitter's Bootstrap! At the moment this is the default page, feel free to modify it to either redirect to a controller or display whatever content you may choose. Below is a list of controllers that are currently deployed in this application, click on each to execute its default action:</p>
                <p><a class="btn btn-primary btn-large" href="http://grails.org/doc/latest/guide/theWebLayer.html#controllers">Learn more &raquo;</a></p>
              </div>
              <div class="row-fluid">
                <h2>Available Controllers:</h2>
                <g:each var="c" in="${grailsApplication.controllerClasses.sort { it.fullName } }">
                    <div class="span4">
                        <h2>${c.logicalPropertyName}</h2>
                        <p>${c.fullName}</p>
                        <g:link class="btn" controller="${c.logicalPropertyName}">
                            Launch ${c.logicalPropertyName}
                        </g:link>
                    </div><!--/span4-->
                </g:each>
              </div><!--/row-->
            </div><!--/span-->
          </div><!--/row-->

          <hr/>

          <footer>
            <p>Generated by <a href="https://github.com/genttool/grails-bootstrap.gent">GENT</a> &copy; 2012 the Gent project</p>
          </footer>

        </div><!--/.fluid-container-->

    </body>
</html>
